# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 965f76352dfd46d815b7117a47753ff76c5b06c6656391ad5413c0cabaff7c0ed0f89b96af0b2782683bb75c518cfbbf67f77d770d08569f741dd420f66de878

test:
  secret_key_base: bdb534f3716895b7b13945b6327d82b855043fcc036541471a94db2c827e6ba06e46bb6cc63aab527733bb33d4680dba7f5d260b39d998dee5540b6ee98d533a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
